version: "3.7"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Un!q@to2023
      MSSQL_PID: Developer
    ports:
      - "1433:1433"

  myapp:
    build: ./php-mssql-apache2/. 
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
